### ISSUE TITLE
Where does the development take place?

### ISSUE THREAD

**Issue by jonasstein** [jschrod/xindy.ctan#5]
Some distribute xindy-2.5.1 
https://repology.org/projects/?search=xindy
But it is not available here.

https://sourceforge.net/projects/xindy/
seems to be maintained by user jschrod too but it is dead since  2013-05-13.

http://www.xindy.org/ links to SF and has several dead links. Who maintains this page? Should xindy.org link to this github repository?

**Comment by jschrod** [comment]
xindy is maintained as part of TeX-Live. (You know this, since I told you so in an email exchange in November 2017.) The reference source lives there.

I tried to mirror the current state of TeX-Live to this Github repository; but getting rid of the TL infrastructure to make a standalone distribution was too much work.

Thus, currently there doesn't exist an upstream distribution any more, neither source nor binary.

You are right that the Web site should be updated to mention that.

**Comment by jschrod** [comment]
Oh yes - and development consists only of bug fixing.

Currently there are no plans for enhancements.
